export type Descriptor =
  | 'accelerometer'
  | 'accessibility-events'
  | 'ambient-light-sensor'
  | 'background-sync'
  | 'camera'
  | 'captured-surface-control'
  | 'clipboard-read'
  | 'clipboard-write'
  | 'geolocation'
  | 'gyroscope'
  | 'local-fonts'
  | 'magnetometer'
  | 'microphone'
  | 'midi'
  | 'notifications'
  | 'payment-handler'
  | 'persistent-storage'
  | 'push'
  | 'screen-wake-lock'
  | 'storage-access'
  | 'top-level-storage-access'
  | 'window-management';

export type IPermissionDescriptor = PermissionDescriptor | { name: Descriptor };
